const flavors=[
{name:'Berry Blast',slug:'berry-blast',image:'berry-blast-3d.png',color:'#cf5dff',rgb:'207,93,255',desc:'Sweet berry punch with a vivid, juicy finish.'},
{name:'Watermelon Ice',slug:'watermelon-ice',image:'watermelon-ice-3d.png',color:'#6cffaf',rgb:'108,255,175',desc:'Juicy watermelon with a crisp cooling edge.'},
{name:'Tropical Island',slug:'tropical-island',image:'tropical-island-3d.png',color:'#ffae42',rgb:'255,174,66',desc:'Bright tropical fruit character with a sunny finish.'},
{name:'Energy Drink',slug:'energy-drink',image:'energy-drink-3d.png',color:'#3e72ff',rgb:'62,114,255',desc:'A sharp, classic energy-drink-inspired profile.'},
{name:'Fresh Mint',slug:'fresh-mint',image:'fresh-mint-3d.png',color:'#5cf59b',rgb:'92,245,155',desc:'Cold, clean mint with an icy visual identity.'},
{name:'Cola',slug:'cola',image:'cola-3d.png',color:'#d46a3f',rgb:'212,106,63',desc:'Dark cola character with a crisp iced edge.'},
{name:'Cappuccino',slug:'cappuccino',image:'cappuccino-3d.png',color:'#d5a162',rgb:'213,161,98',desc:'Creamy coffeehouse character with roasted depth.'}
];
const strengths={75:{price:4,caffeine:'75 mg',theanine:'100 mg',alpha:'50 mg',vitd:'5 µg'},150:{price:5,caffeine:'150 mg',theanine:'150 mg',alpha:'100 mg',vitd:'5 µg'},250:{price:6,caffeine:'250 mg',theanine:'200 mg',alpha:'150 mg',vitd:'10 µg'}};
let currentFlavor=0,currentStrength=75,cart=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const heroImage=$('#heroImage'),heroFlavor=$('#heroFlavor'),heroPrice=$('#heroPrice');
function setAccent(f){document.documentElement.style.setProperty('--accent',f.color);document.documentElement.style.setProperty('--accent-rgb',f.rgb)}
function selectFlavor(i,scroll=false){currentFlavor=i;const f=flavors[i];setAccent(f);heroImage.style.opacity='0';heroImage.style.transform='scale(.975)';setTimeout(()=>{heroImage.src=f.image;heroImage.alt=`${f.name} 69 caffeine pouch tin, 3D concept render`;heroImage.style.opacity='1';heroImage.style.transform='none'},130);heroFlavor.textContent=f.name;$$('.hero-selector button').forEach((b,n)=>b.classList.toggle('active',n===i));if(scroll)document.querySelector('.hero').scrollIntoView({behavior:'smooth'})}
function selectStrength(mg){currentStrength=Number(mg);const d=strengths[currentStrength];heroPrice.textContent=`$${d.price}`;$$('.strength-card').forEach(b=>b.classList.toggle('active',Number(b.dataset.strength)===currentStrength));$$('#formulaStrengthSelector button').forEach(b=>b.classList.toggle('active',Number(b.dataset.strength)===currentStrength));$$('.strength-mini button').forEach(b=>b.classList.toggle('active',Number(b.dataset.strength)===currentStrength));$('[data-key=caffeine]').textContent=d.caffeine;$('[data-key=theanine]').textContent=d.theanine;$('[data-key=alpha]').textContent=d.alpha;$('[data-key=vitd]').textContent=d.vitd}
function buildHeroSelector(){const w=$('#heroSelector');flavors.forEach((f,i)=>{const b=document.createElement('button');b.type='button';b.style.background=f.color;b.className=i===0?'active':'';b.setAttribute('aria-label',f.name);b.onclick=()=>selectFlavor(i);w.appendChild(b)})}
function buildFlavorGrid(){const grid=$('#flavorGrid');flavors.forEach((f,i)=>{const card=document.createElement('article');card.className='flavor-card reveal';card.style.setProperty('--local',f.color);card.style.setProperty('--local-rgb',f.rgb);card.innerHTML=`<div class="flavor-card-head"><span>0${i+1} / FLAVOR</span><span>69</span></div><div class="flavor-visual"><img src="${f.image}" loading="lazy" alt="${f.name} 69 caffeine pouch 3D tin"></div><div class="flavor-card-bottom"><div><h3>${f.name}</h3><p>${f.desc}</p><div class="strength-mini">${[75,150,250].map(s=>`<button type="button" data-strength="${s}" class="${s===currentStrength?'active':''}">${s} MG</button>`).join('')}</div></div><button class="add-button" type="button" aria-label="Add ${f.name} to cart">+</button></div>`;card.querySelector('.flavor-visual').onclick=()=>selectFlavor(i,true);card.querySelectorAll('.strength-mini button').forEach(b=>b.onclick=e=>{e.stopPropagation();selectStrength(b.dataset.strength)});card.querySelector('.add-button').onclick=()=>addToCart(i);grid.appendChild(card)})}
function addToCart(i){const s=strengths[currentStrength];cart.push({id:Date.now()+Math.random(),flavor:i,strength:currentStrength,price:s.price});renderCart();showToast(`${flavors[i].name} · ${currentStrength} mg added`)}
function addBundle(type){const map={starter:[0,4,1],discovery:[0,1,2,3,4,5,6],focus:[3,5,6]};(map[type]||[]).forEach(i=>cart.push({id:Date.now()+Math.random(),flavor:i,strength:currentStrength,price:strengths[currentStrength].price}));renderCart();showToast(`${type==='discovery'?'All 7 flavors':'Bundle'} added at ${currentStrength} mg`)}
function renderCart(){const list=$('#cartItems');$('#cartCount').textContent=cart.length;list.innerHTML='';$('#cartEmpty').style.display=cart.length?'none':'flex';cart.forEach(item=>{const f=flavors[item.flavor];const el=document.createElement('div');el.className='cart-item';el.innerHTML=`<img src="${f.image}" alt=""><div><strong>${f.name}</strong><small>${item.strength} mg · $${item.price}</small></div><button type="button" aria-label="Remove">×</button>`;el.querySelector('button').onclick=()=>{cart=cart.filter(x=>x.id!==item.id);renderCart()};list.appendChild(el)});$('#cartTotal').textContent=`$${cart.reduce((sum,x)=>sum+x.price,0)}`}
function openCart(v=true){$('#cartDrawer').classList.toggle('open',v);$('#cartDrawer').setAttribute('aria-hidden',String(!v));document.body.style.overflow=v?'hidden':''}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),1900)}
buildHeroSelector();buildFlavorGrid();selectStrength(75);setAccent(flavors[0]);
$$('.strength-card').forEach(b=>b.onclick=()=>selectStrength(b.dataset.strength));$$('#formulaStrengthSelector button').forEach(b=>b.onclick=()=>selectStrength(b.dataset.strength));$$('.bundle-add').forEach(b=>b.onclick=()=>addBundle(b.dataset.bundle));$('#cartButton').onclick=()=>openCart(true);$('#cartClose').onclick=()=>openCart(false);$('#cartBackdrop').onclick=()=>openCart(false);$('#checkoutDemo').onclick=()=>showToast('Demo only — checkout not connected yet');$('#waitlistForm').onsubmit=e=>{e.preventDefault();showToast('Waitlist demo — email not sent');e.target.reset()};document.addEventListener('keydown',e=>{if(e.key==='Escape')openCart(false)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.1});$$('.reveal').forEach(el=>observer.observe(el));
document.addEventListener('mousemove',e=>{const glow=$('.cursor-glow');if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}const wrap=$('#heroImageWrap');if(!wrap)return;const r=wrap.getBoundingClientRect();if(e.clientX>r.left&&e.clientX<r.right&&e.clientY>r.top&&e.clientY<r.bottom){const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;wrap.style.transform=`perspective(900px) rotateX(${-y*5}deg) rotateY(${x*7}deg) translateY(${y*5}px)`}});$('#heroImageWrap').addEventListener('mouseleave',()=>$('#heroImageWrap').style.transform='none');
let auto=0;setInterval(()=>{if(document.visibilityState==='visible'){auto=(auto+1)%flavors.length;selectFlavor(auto)}},7000);
